# Generated by Django 4.1.6 on 2023-02-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Archinkluencer", "0002_modeldataifc_doorpos_modeldataifc_length_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modeldataifc",
            name="done",
        ),
        migrations.AddField(
            model_name="modeldataifc",
            name="algo",
            field=models.CharField(
                choices=[("Algo1", "Algo1"), ("Algo2", "Algo2")],
                max_length=200,
                null=True,
            ),
        ),
    ]
