# Generated by Django 4.1.6 on 2023-02-16 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Archinkluencer", "0003_remove_modeldataifc_done_modeldataifc_algo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modeldataifc",
            name="algo",
            field=models.CharField(
                choices=[("Algo1", "Algo1"), ("Algo2", "Algo2")],
                default=django.utils.timezone.now,
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
